/* eslint-disable comma-dangle */
const wander = { // eslint-disable-line no-unused-vars
  consoles: [
    // BEGIN AUTO GENERATED FROM ../wander.md.
    'https://susam.net/wander/',
    'https://dahlstrand.net/wander/',
    'https://www.siddharthagolu.com/wander/',
    'https://juleskourelakos.com/wander/',
    'https://bitzero.cloud/wander/',
    'https://matkelly.com/wander/',
    'https://www.davidtran.me/wander/',
    'https://martincapodici.com/wander/',
    'https://mkprc.xyz/wander/',
    'https://astandke.com/wander/',
    'https://bjro.dev/wander/',
    'https://joshing.you/wander/',
    'https://huffstler.github.io/wander/',
    'https://www.acdw.net/wander/',
    'https://fractaldragon.net/wander/',
    'https://4thguy.codeberg.page/wander/',
    'https://benovermyer.com/wander/',
    'https://tony-zorman.com/wander/',
    'https://heitorpb.github.io/wander/',
    'https://wander.blog.eric-bml.net/',
    'https://tuftel.today/wander/',
    'https://www.carlwarnick.com/wander/',
    'https://arkholt.com/wander/',
    'https://blog.gridranger.dev/wander/',
    'https://aartaka.me/wander/',
    'https://wander.lordmatt.co.uk/',
    'https://exurd.neocities.org/wander/',
    'https://wander.chilli.sh/',
    'https://ink.imavinash.net/wander/',
    'https://wander.twixter.eu/',
    'https://punkto.org/wander/',
    'https://cogdogblog.com/wander/',
    'https://heckmeck.de/wander/',
    'https://douglascuthbertson.com/wander/',
    'https://antonio.is/wander/',
    'https://pnppl.cc/app/wander/',
    'https://hugo0.com/wander/',
    'https://bruff.gay/wander/',
    'https://dawnreed.net/wander/',
    'https://exurd.neocities.org/wander/words/',
    // END AUTO GENERATED.
  ],
  pages: [],
  ignore: [],
}
